apiVersion: v1
kind: Config
clusters:
- name: "production"
  cluster:
    server: "https://rancher.citymall.live/k8s/clusters/local"

users:
- name: "production"
  user:
    token: "kubeconfig-u-dqn6kydejk2xgkc:z4rthc954k7shw4n79wjmshz6rt29bcgs68xzx7pcrszsgvjqfkhrm"


contexts:
- name: "production"
  context:
    user: "production"
    cluster: "production"

current-context: "production"
